name: Frontend to DigitalOcean Spaces

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: |
          cd ./QuizCraft.Frontend
          npm install

      - name: Build React app
        run: |
          cd ./QuizCraft.Frontend
          npm run build

      - name: Install doctl
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/latest/download/doctl-$(uname)-$(uname -m).tar.gz | tar -xzv
          sudo mv doctl /usr/local/bin/

      - name: Authenticate doctl
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: doctl auth init

      - name: Upload files to Space
        env:
          SPACE_NAME: ${{ secrets.DIGITALOCEAN_SPACE_NAME }}
          SPACE_REGION: ${{ secrets.DIGITALOCEAN_SPACE_REGION }}
        run: |
          doctl spaces cp --recursive ./QuizCraft.Frontend/build/ s3://${{ secrets.DIGITALOCEAN_SPACE_NAME }}/